# Generated by Django 4.2.3 on 2023-07-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribe', models.CharField(max_length=50)),
                ('recipeType', models.CharField(max_length=200)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('ingredientsQty', models.TextField(blank=True, null=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
